baseURL = "https://zhiq.dev/"
local = "zh-CN"
title = "ZhiQ"
theme = "PaperMod"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.link]
        useEmbedded = "always"
